In [8]:
import h5py
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [9]:
# Step 1: Load the data
mat_file = r'E:\Thesis\thesis_code\data\rp\100Mbps_features.h5'   # change path

In [10]:
with h5py.File(mat_file, 'r') as f:
    X = np.array(f['features'])          # Features
    y = np.array(f['label_type'])        # Labels
    z = np.array(f['label_length'])     # Length labels (if needed)

print("Feature shape:", X.shape)
print("Label shape:", y.shape)

Feature shape: (39525, 30)
Label shape: (39525,)


In [11]:
print(X[:5])
print(y[:5])
print(z[:5])

[[ 8.87011141e-02 -5.18721854e-03  8.87793750e-02  3.72685492e-03
  -9.56013083e-01  1.60400391e-01  1.22376108e+00  2.21100616e+00
   1.80673039e+00  2.69810295e+00  9.08005676e+01  1.41525270e+07
   9.27977676e+01  1.83029180e+07  9.36494980e+01  1.34811400e+07
   9.38494492e+01  1.42135620e+07  1.03335030e+02  1.33590700e+07
   1.03878395e+02  1.76925660e+07  1.06052086e+02  1.82418820e+07
   1.06219269e+02  1.61666870e+07  1.09588593e+02  1.34201050e+07
   1.24886101e+02  1.62277220e+07]
 [ 8.88449922e-02 -5.51049411e-03  8.89246389e-02  3.76266241e-03
  -9.50737417e-01  1.59301758e-01  1.23132527e+00  2.20582604e+00
   1.79142439e+00  2.69984317e+00  9.14563599e+01  1.28097530e+07
   9.15961838e+01  1.41525270e+07  9.49334030e+01  1.42135620e+07
   9.77132034e+01  1.34811400e+07  1.01073181e+02  1.33590700e+07
   1.04983353e+02  1.76925660e+07  1.05742500e+02  1.61666870e+07
   1.06937630e+02  1.34201050e+07  1.08572914e+02  1.82418820e+07
   1.26029144e+02  1.62277220e+07]
 [ 8.8

In [12]:
unique_samples = np.unique(X, axis=0)

print("Original:", X.shape[0])
print("Unique:", unique_samples.shape[0])

Original: 39525
Unique: 39525


In [13]:
unique, counts = np.unique(y, return_counts=True)

for u, c in zip(unique, counts):
    print(u, c)

0 10000
1 10000
2 9525
3 10000


In [7]:
unique, counts = np.unique(z, return_counts=True)

for u, c in zip(unique, counts):
    print(u, c)

0.0 11254
5.0 2257
10.0 2252
15.0 2260
20.0 2232
25.0 2249
30.0 2246
35.0 2247
40.0 2153
45.0 2250
50.0 4497
100.0 2250
150.0 2274
200.0 2244


In [8]:
# Optional: flatten labels if needed
y = y.ravel()

In [9]:
# Step 2: Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)



In [10]:
# Step 3: Create Random Forest model
rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=None,
    random_state=42,
    n_jobs=-1
)



In [11]:
scores = cross_val_score(rf_model, X, y, cv=5)

In [12]:
scores

array([0.86944972, 0.98697027, 0.99949399, 0.999747  , 0.74927261])

In [13]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

In [14]:
# Step 4: Train model
rf_model.fit(X_train, y_train)

# Step 5: Predict
y_pred = rf_model.predict(X_test)

# Step 6: Evaluation
accuracy = accuracy_score(y_test, y_pred)

print(f"\nAccuracy: {accuracy:.4f}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Accuracy: 0.9980

Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      2000
           1       1.00      0.99      1.00      2000
           2       1.00      1.00      1.00      1905
           3       1.00      1.00      1.00      2000

    accuracy                           1.00      7905
   macro avg       1.00      1.00      1.00      7905
weighted avg       1.00      1.00      1.00      7905


Confusion Matrix:
[[1999    1    0    0]
 [  15 1985    0    0]
 [   0    0 1905    0]
 [   0    0    0 2000]]


In [15]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred = rf_model.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1999    1    0    0]
 [  15 1985    0    0]
 [   0    0 1905    0]
 [   0    0    0 2000]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      2000
           1       1.00      0.99      1.00      2000
           2       1.00      1.00      1.00      1905
           3       1.00      1.00      1.00      2000

    accuracy                           1.00      7905
   macro avg       1.00      1.00      1.00      7905
weighted avg       1.00      1.00      1.00      7905

